name: Maven Package

on:
  pull_request:
    branches: []

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Maven project (skip tests)
        run: |
          mvn clean install --file 'PasswordMinTimePolicy/pom.xml' -Dmaven.test.skip

      - name: Pull Keycloak with Docker
        run: |
          docker run -d --name=keycloak -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak start-dev
      - name: Docker processes
        run: |
          docker cp PasswordMinTimePolicy/target/*.jar keycloak:opt/keycloak/providers
          docker restart keycloak
      - name: wait until docker is finished (keycloak is available)
        run: |
          while ! curl --output /dev/null --silent --head --fail http://localhost:8080; do sleep 1 && echo -n .; done;
      
      - name: Build Maven project (with tests)
        run: |
          mvn clean install --file 'PasswordMinTimePolicy/pom.xml'
          mkdir staging && cp PasswordMinTimePolicy/target/*.jar staging

      - name: Set up a cache for Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Persist workflow data as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: github-actions-artifact
          path: staging